services:
  - type: web
    name: sales-tracker-backend
    env: python
    region: frankfurt
    rootDir: sales_backend/sales_backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn sales_tracker.wsgi:application --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sales-tracker-db
          property: connectionString
      - key: CORS_ALLOW_ALL_ORIGINS
        value: True
      - key: FRONTEND_URL
        value: https://sales-tracker-pro-v3.vercel.app
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_PORT
        value: 587
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false

databases:
  - name: sales-tracker-db
    region: frankfurt
    plan: free
    databaseName: sales_db
    user: sales_user
