# Generated by Django 5.2.5 on 2025-09-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientinvitation_owner_userprofile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinvitation',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientinvitation',
            name='invitation_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientinvitation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
