# Generated by Django 5.2.5 on 2025-09-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientinvitation_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('used', 'Utilisée'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
