# Generated by Django 5.2.5 on 2025-09-01 20:30

import django.db.models.deletion
import sales.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=sales.models.profile_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Modèle',
                'verbose_name_plural': 'Profils Modèles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='sales.modelprofile')),
            ],
            options={
                'verbose_name': 'Vente Quotidienne',
                'verbose_name_plural': 'Ventes Quotidiennes',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('model_profile', 'date', 'amount_usd', 'created_at')},
            },
        ),
    ]
