# Generated by Django 5.2.5 on 2025-09-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_modelprofile_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
